disabled_rules:
  - trailing_whitespace
  - identifier_name
  - private_over_fileprivate
  - nesting
  - force_try
  - force_cast
  - multiple_closures_with_trailing_closure
  - redundant_optional_initialization

line_length: 240
large_tuple:
  warning: 4
  error: 5
